-- Generated by Mocodo 4.3.2

CREATE TYPE gameboard_category AS ENUM ('puzzle', 'deck building', 'narrative');

CREATE TABLE client (
  PRIMARY KEY (client_id),
  client_id   SERIAL NOT NULL,
  client_name TEXT NOT NULL,
  email       TEXT NOT NULL,
  password    TEXT NOT NULL,
  birthdate   DATE NOT NULL
);

CREATE TABLE gameboard (
  PRIMARY KEY (gameboard_id),
  gameboard_id    SERIAL NOT NULL,
  title           TEXT NOT NULL,
  description     TEXT,
  category        gameboard_category,
  publisher_id    SERIAL NOT NULL,
  publishing_date DATE NOT NULL,
  nb_players  SMALLSERIAL NOT NULL CHECK(nb_players > 0) 
);

CREATE TABLE publisher (
  PRIMARY KEY (publisher_id),
  publisher_id   SERIAL NOT NULL,
  publisher_name TEXT NOT NULL
);

CREATE TABLE purchase (
  client_id     SERIAL NOT NULL,
  gameboard_id  SERIAL NOT NULL,
  purchase_date DATE NOT NULL DEFAULT CURRENT_DATE,
  quantity  INTEGER NOT NULL
);

ALTER TABLE gameboard ADD FOREIGN KEY (publisher_id) REFERENCES publisher (publisher_id);

ALTER TABLE purchase ADD FOREIGN KEY (gameboard_id) REFERENCES gameboard (gameboard_id);
ALTER TABLE purchase ADD FOREIGN KEY (client_id) REFERENCES client (client_id);
